# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Encourage Marketing
email: support@encouragemarketing.com
description: > # this means to ignore newlines until "baseurl:"
  Encourage Marketing creates custom smartphone applications for veterinary clinics. The apps, compatible with iPhone and Android, are powerful marketing tools that encourage repeat business by building a close connection with your clients.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://encouragemarketing.com" # the base hostname & protocol for your site
twitter_username: encouragemarket
github_username:  encouragemarketing

# Build settings
markdown: kramdown
